"""Render the command reference from the registry, so the docs cannot drift from the code.

Two artifacts come out of the same data as ``--help``: a table plus one section per command for the
README, and a plain-text HELP.md holding every parser's help exactly as a terminal would print it.
"""

from __future__ import annotations

import argparse
import contextlib
import io

from .cli import PROGRAM, build_parser
from .registry import CliCommand, CliParameter, groups

BEGIN_MARKER = "<!-- BEGIN-GENERATED: ixd -->"

END_MARKER = "<!-- END-GENERATED: ixd -->"

HELP_HEADER = f"""# {PROGRAM} help

Generated by `{PROGRAM} docs`; every word below comes from a command's docstring and signature.
"""


def anchor(command: CliCommand) -> str:
    """The in-page link target for a command's README section.

    :param command: the command to link to
    :return: a GitHub heading anchor such as ``#ixd-wt-sync``
    """
    return "#" + f"{PROGRAM} {command.path}".replace(" ", "-")


def cell(text: str) -> str:
    """Make text safe for a markdown table cell.

    :param text: a summary that may hold pipes or newlines
    :return: the text on one line with its pipes escaped
    """
    return " ".join(text.split()).replace("|", "\\|")


def usage(command: CliCommand) -> str:
    """The one-line invocation for a command.

    :param command: the command to spell out
    :return: the command words followed by its arguments, optional ones in brackets
    """
    parts = [PROGRAM, command.path]
    for parameter in command.params:
        word = parameter.name.upper() if parameter.positional else parameter.flag
        if parameter.positional and parameter.multiple:
            word += " ..."
        elif not parameter.positional and parameter.annotation is not bool:
            word += " " + parameter.name.replace("_", "-").upper()
        parts.append(f"[{word}]" if parameter.has_default else word)
    return " ".join(parts)


def parameter_row(parameter: CliParameter) -> str:
    """One markdown table row describing a parameter.

    :param parameter: the parameter to describe
    :return: a table row of name, default and help text
    """
    if parameter.positional:
        name = parameter.name.upper()
    elif parameter.short:
        name = f"`{parameter.short}`, `{parameter.flag}`"
    else:
        name = f"`{parameter.flag}`"
    if parameter.choices:
        name += " " + " \\| ".join(f"`{choice}`" for choice in parameter.choices)
    if not parameter.has_default:
        default = "required"
    elif parameter.annotation is bool:
        default = "off" if not parameter.default else "on"
    elif parameter.default in ("", None, (), []):
        default = "—"
    else:
        default = f"`{parameter.default}`"
    return f"| {name} | {default} | {cell(parameter.help_text)} |"


def command_section(command: CliCommand) -> list[str]:
    """The README section for one command.

    :param command: the command to document
    :return: the markdown lines of its section
    """
    lines = [f"### {PROGRAM} {command.path}", "", command.summary, "", "```", usage(command), "```", ""]
    if command.detail:
        lines += [command.detail, ""]
    if command.params:
        lines += ["| argument | default | meaning |", "| --- | --- | --- |"]
        lines += [parameter_row(parameter) for parameter in command.params]
        lines += [""]
    return lines


def reference() -> str:
    """The whole generated README region: a summary table then a section per command.

    :return: the markdown between the generated-region markers
    """
    lines = [BEGIN_MARKER, "", "| command | what it does |", "| --- | --- |"]
    for commands in groups().values():
        for command in commands:
            lines.append(f"| [`{PROGRAM} {command.path}`]({anchor(command)}) | {cell(command.summary)} |")
    lines.append("")
    for group, commands in groups().items():
        lines += [f"## {group}", ""]
        for command in commands:
            lines += command_section(command)
    lines.append(END_MARKER)
    return "\n".join(lines)


def parser_help(parser: argparse.ArgumentParser) -> str:
    """The help text a parser prints, captured as a string.

    :param parser: the parser to ask
    :return: everything it would write to stdout
    """
    buffer = io.StringIO()
    with contextlib.redirect_stdout(buffer):
        parser.print_help()
    return buffer.getvalue().rstrip()


def subparsers_of(parser: argparse.ArgumentParser) -> dict[str, argparse.ArgumentParser]:
    """The named parsers one parser dispatches to.

    :param parser: a parser that may hold a subparser action
    :return: the word that selects each parser, mapped to that parser
    """
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            return dict(action.choices)
    return {}


def help_document() -> str:
    """Every parser's help, top level first, in the order a user meets them.

    :return: the full text of HELP.md
    """
    root = build_parser()
    blocks = [HELP_HEADER, "```", parser_help(root), "```"]
    for word, group_parser in subparsers_of(root).items():
        blocks += [f"## {PROGRAM} {word}", "```", parser_help(group_parser), "```"]
        for name, command_parser in subparsers_of(group_parser).items():
            blocks += [f"### {PROGRAM} {word} {name}", "```", parser_help(command_parser), "```"]
    return "\n".join(blocks) + "\n"


def replace_region(text: str, region: str) -> str:
    """Swap the generated region of a document, or append it when the markers are absent.

    :param text: the current document
    :param region: the generated block, markers included
    :return: the document with the region in place
    :raises ValueError: when only one of the two markers is present
    """
    if BEGIN_MARKER in text and END_MARKER in text:
        head = text.split(BEGIN_MARKER)[0]
        tail = text.split(END_MARKER)[1]
        return head + region + tail
    if BEGIN_MARKER in text or END_MARKER in text:
        raise ValueError("the generated region has only one of its two markers; fix the file by hand")
    return text.rstrip() + "\n\n" + region + "\n"
